# -*- coding: utf-8 -*-
"""GANILLA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H8CJ5LfK6-95d6Mtc3ospjrrOBzQIyuq
"""

from tensorflow.keras.models import Model, load_model
from tensorflow.keras.losses import binary_crossentropy, mse
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Conv2D, ReLU, Concatenate, Input, MaxPool2D, Conv2DTranspose, UpSampling2D, Add, LeakyReLU, Flatten, Dense
from keras_contrib.layers import InstanceNormalization
from sklearn.utils import shuffle
from datetime import datetime
import numpy as np
import cv2
import os

n_run = 3
if not os.path.exists(f"./examples/run{n_run}"):
  os.mkdir(f"./examples/run{n_run}")
PATH_TO_ORIGINAL = f"./examples/run{n_run}/original/"
if not os.path.exists(PATH_TO_ORIGINAL):
  os.mkdir(PATH_TO_ORIGINAL)
PATH_TO_FAKE =  f"./examples/run{n_run}/fake/"
if not os.path.exists(PATH_TO_FAKE):
  os.mkdir(PATH_TO_FAKE)
PATH_TO_MODELS = f"./models/run{n_run}/"
DATASET = "human_simpson"
models = [f'g_BA_{i}.h5' for i in [6800]]
batch_size = 4

trainB_flow = ImageDataGenerator()
trainB = trainB_flow.flow_from_directory(directory=f"./datasets/{DATASET}",
                                classes=["trainB"],
                                batch_size=batch_size)

for fmodel in models:
  g_BA = load_model(os.path.join(PATH_TO_MODELS, fmodel), custom_objects={"InstanceNormalization":InstanceNormalization})
  images, _  = next(trainB)
  images_converted = g_BA.predict(images)
  model_num = fmodel[5:-3]
  for k, img_conv in enumerate(images_converted):
    reshaped_conv = img_conv.reshape((256,256,3))
    rgb_conv = cv2.cvtColor(reshaped_conv, cv2.COLOR_BGR2RGB)
    cv2.imwrite(os.path.join(PATH_TO_FAKE, f"fake{model_num}_{k}.png"),rgb_conv)
  for k, img in enumerate(images):
      reshaped_img = img.reshape((256,256,3))
      rgb = cv2.cvtColor(reshaped_img, cv2.COLOR_BGR2RGB)
      cv2.imwrite(os.path.join(PATH_TO_ORIGINAL, f"original{model_num}_{k}.png"),rgb)
